// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(gestorDbContext))]
    partial class gestorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Modelos.Elemento", b =>
                {
                    b.Property<long>("idElemento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idElemento"));

                    b.Property<int>("cantidadElemento")
                        .HasColumnType("integer");

                    b.Property<string>("codigoElemento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcionElemento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreElemento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idElemento");

                    b.ToTable("Elementos");
                });

            modelBuilder.Entity("DAL.Modelos.RelElementoReservas", b =>
                {
                    b.Property<long>("idRelElementoReservas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idRelElementoReservas"));

                    b.Property<int>("cantidadReservada")
                        .HasColumnType("integer");

                    b.Property<long>("idElemento")
                        .HasColumnType("bigint");

                    b.Property<long>("idReserva")
                        .HasColumnType("bigint");

                    b.HasKey("idRelElementoReservas");

                    b.HasIndex("idElemento");

                    b.HasIndex("idReserva");

                    b.ToTable("RelElementosReservas");
                });

            modelBuilder.Entity("DAL.Modelos.Reserva", b =>
                {
                    b.Property<long>("idReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idReserva"));

                    b.Property<DateTime>("fchReserva")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("idReserva");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("DAL.Modelos.RelElementoReservas", b =>
                {
                    b.HasOne("DAL.Modelos.Elemento", "Elemento")
                        .WithMany()
                        .HasForeignKey("idElemento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Modelos.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("idReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elemento");

                    b.Navigation("Reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
